### ISSUE TITLE
make bug with QT

### ISSUE THREAD

**Issue by agnescameron** [Pold87/blockchain-swarm-robotics#1]
hi -- 

running `./install_scripts.sh` (on both OSX and Linux (Ubuntu), with both Qt5 and Qt4 installed) returns the error:
```
/Users/.../blockchain-swarm-robotics/scripts/argos3-epuck/src/plugins/robots/e-puck/real_robot/vision/epuck_camera_client_blob_detector_configurator.h:8:10: fatal error: 
      'QSpinBox' file not found
#include <QSpinBox>
         ^~~~~~~~~~
```
Was wondering if you knew a fix for this? Looks like a really interesting repo, would love to get it working!

(for reference: I've successfully built and run ArGos before)

**Comment by Pold87** [comment]
Hi,

I think you can get rid of this error if you install all the requirements mentioned at
https://github.com/ilpincy/argos3#debian

Could you please let me know if you manage to get it working?

By the way, we're still working on a cleaned-up and more versatile version of this repository (originally the code had some hard-coded settings for our computer cluster). Also, we'll record a video about how to install the software.

I made a lot of changes after you forked the code (mainly in geth_static.cpp); it should work on all platforms now (with some tweaking). It's maybe a good idea to check the updates regularly.

In the updated README file (https://github.com/Pold87/blockchain-swarm-robotics#instructions) you can find a link to a virtual machine image (.ova) with a working version.

**Comment by agnescameron** [comment]
thanks so much Volker! `./install_scripts` now gets all the way through on Ubuntu, still fails on mac (using the requirements listed for https://github.com/ilpincy/argos3#mac-osx). Potentially it's looking for `.so` files (rather than `.dylib`).

Now throwing a bunch of errors with `cmake ..`:  there were a couple of paths that seemed to be hardcoded, but even after I get rid of them, it has trouble finding `ci_controller.h` in `argos3`. It might still be a problem with the file-paths -- I'll let you know if I find it. If it sounds like a familiar bug it would be good to know!

thanks again

**Comment by Pold87** [comment]
Thanks for reporting back, great that the installation worked! 

I am not sure about the cmake error. Maybe it helps to execute the setup script that is created by
`install_argos.sh` (take care to use the latest version of `install_argos.sh`, there was a bug in a previous version that has overwritten the $PATH variable). The script should be executed everytime you want to run ARGoS, so it's maybe best to add the setup script to your `.bashrc`; I have the following line in my `.bashrc`:
`source "~/argos3-dist/bin/setup_argos3"`

I'll look into why the installation fails on Mac.

**Comment by agnescameron** [comment]
ah -- thanks! I'm now really close...

The previous bug turned out to be a problem with `ga` -- installing `libga` using `apt-get` didn't cut it. Running `source "~/argos3-dist/bin/setup_argos3"` also fixed an error that came after that, that's a really helpful line! Sadly, `make` also fails (though potentially for a more helpful reason). I get a failed `#include`:

```
fatal error: argos3/plugins/robots/e-puck/control_interface/ci_epuck_range_and_bearing_actuator.h: No such file or directory
```
Interestingly, the point where this fails is in `epuck_environment_classification.h`, and before this, it happily runs the lines:

```
#include <argos3/core/control_interface/ci_controller.h>
#include <argos3/core/utility/configuration/argos_configuration.h>
#include <argos3/plugins/robots/e-puck/control_interface/ci_epuck_range_and_bearing_a...$
```
before failing on the third. This means that it's definitely happy finding argos core (so the path is ok), but it's not so happy with the plugins. Could I be missing a package?

**Comment by agnescameron** [comment]
also -- this is really helpful, thanks! I'm keeping a note of everything I've done, I can send once it's building if you like.
