### ISSUE TITLE
waiting for 5 blocks to confirm

### ISSUE THREAD

**Issue by amartyahatua** [Pold87/blockchain-swarm-robotics#2]
Hi,
When I am running start_experiment1.sh it's not stopping and always a message  "waiting for 5 blocks to confirm" is coming.

**Comment by Pold87** [comment]
First of all, I'm very sorry for the late reply.

Have you tried to let the experiment run for some time (maybe hours)? Then you can check if there is  file with the extension .RUNS in the folder data/. This file states the consensus time and whether the robots found consensus on white or black. 

In general, the message "waiting for 5 blocks to confirm" is a default log message from geth, so it means that geth is running fine and that it's mining blocks.
