### ISSUE TITLE
Stable Block calculation

### ISSUE THREAD

**Issue by Ishita2509** [Pold87/blockchain-swarm-robotics#4]
Hey!
I was trying to understand the code of Smart Contract and was having the hard time understanding the stableBlock calculation. Why did you take the max with int(0) when your firstBlock is set as 1150000? Also how did you decide upon the blockDelay?  Any help will be greatly appreciated.
Thanks.

**Comment by Pold87** [comment]
Hi, thanks for your questions!

If I remember correctly, the statement `uint constant firstBlock = 1150000`; comes from some debugging using https://remix.ethereum.org/. The blockchain actually used starts at block 0. 

Regarding the stableBlock calculation, I copied a footnote from your paper "Managing Byzantine Robots via Blockchain Technology in a Swarm Robotics Collective Decision Making Scenario":

We define a stable block as the block which has exactly z = 6 confirmations. The
choice of z is a trade-off between speed and security; it has implications for both the
probability of forks to occur and for attacks to be successful. In this paper, we are only
concerned with the influence of z on the probability of forks. If z is chosen too small,
the probability increases that the opinion of a robot is just based on a locally available
fork (and will, therefore, be invalid when the fork is resolved and the majority of the
robots agree on a different blockchain version); if z is chosen too high, it will introduce
delays (i.e., a robot’s opinion will be based on an outdated opinion distribution). In
our experiments, the average block time given the fixed mining difficulty of 106
and fixed total hash power of the robots is approximately 17 seconds. Therefore, z = 6
blocks are mined on average after 102 seconds. The average difference per time step
between the highest and lowest block number of all robots was 8.5 and the average
standard deviation of the differences 2.7. The optimal value for z depends on many
factors, such as the movement of the robots, communication range, number of robots,
and the expected block time.

Please feel free to let me know if you have any other questions.

**Comment by Ishita2509** [comment]
Hey. Thank you so much for the informative reply. If you don't mind, can you please tell if you are running geth process for every robot? I am new to both the simulator as well as blockchain, so having a hard time understanding things. Thanks again.

**Comment by Pold87** [comment]
Yes, every robot is running a separate geth process. Please feel free to ask any other questions, I'm happy to help you.
